# 所有视频格式扩展名字典,值为true
video_formats = {
    "3g2": True,
    "3gp": True,
    "aaf": True,
    "asf": True,
    "avchd": True,
    "avi": True,
    "drc": True,
    "flv": True,
    "m2v": True,
    "m4p": True,
    "m4v": True,
    "mkv": True,
    "mng": True,
    "mov": True,
    "mp2": True,
    "mp4": True,
    "mpe": True,
    "mpeg": True,
    "mpg": True,
    "mpv": True,
    "mxf": True,
    "nsv": True,
    "ogg": True,
    "ogv": True,
    "qt": True,
    "rm": True,
    "rmvb": True,
    "roq": True,
    "svi": True,
    "vob": True,
    "webm": True,
    "wmv": True,
    "yuv": True,
}
# 所有音频格式扩展名字典,值为true
audio_formats = {
    "aac": True,
    "aiff": True,
    "ape": True,
    "au": True,
    "flac": True,
    "gsm": True,
    "it": True,
    "m3u": True,
    "m4a": True,
    "mid": True,
    "mod": True,
    "mp3": True,
    "mpa": True,
    "pls": True,
    "ra": True,
    "s3m": True,
    "sid": True,
    "wav": True,
    "wma": True,
    "xm": True,
}
# 所有图片格式扩展名字典,值为true
image_formats = {
    "bmp": True,
    "gif": True,
    "ico": True,
    "jpeg": True,
    "jpg": True,
    "png": True,
    "psd": True,
    "svg": True,
    "tif": True,
    "tiff": True,
    "webp": True,
}
# 所有文本格式扩展名字典,值为true
text_formats = {
    "doc": True,
    "docx": True,
    "log": True,
    "msg": True,
    "odt": True,
    "pages": True,
    "rtf": True,
    "tex": True,
    "txt": True,
    "wpd": True,
}

# 所有压缩包格式扩展名字典,值为true
zip_formats = {
    "7z": True,
    "rar": True,
    "gz": True,
    "zip": True,
    "bz2": True,
    "tar": True,
}

file_map = {
    "视频": video_formats,
    "音频": audio_formats,
    "图片": image_formats,
    "文本": text_formats,
    "解压": zip_formats,
}
